services:
  postgres:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
    - ${DATABASE_PORT}:5432
    volumes:
      - tech-task-ip-db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - tech-task-ip-redis:/var/lib/redis
      - tech-task-ip-redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  tech-task-ip-db:
  tech-task-ip-redis:
  tech-task-ip-redis-config:
